[package]
name = "thanks"
version = "0.1.0"
authors = ["Mark Rousskov <mark.simulacrum@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
hyperx = "0.14"
dotenv = "0.13"

[dependencies.diesel]
version = "1.4"
features = ["sqlite"]

[dependencies.serde]
version = "1"
features = ["derive"]
